
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-04T13:51:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fec640bc9097c07c7c372e135e7075f60871fac4",
 "version": "3.4+845.gfec640bc"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
